# Generated by Django 4.1.1 on 2022-09-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_accountemailaddress_accountemailconfirmation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountEmailaddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailconfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialaccount',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialapp',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialappSites',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialtoken',
        ),
    ]
